version: 2
jobs:
  build:
    working_directory: ~/angular-with-ci-cd-pipeline
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restoring Dependencies from Cache
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ .Branch }}-
            - dependencies-
      - run:
          name: Installing Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Caching Dependencies
          paths:
            - ~/.cache/yarn
          key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Testing [Unit]
          command: yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: Testing [End-to-End]
          command: yarn e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - store_test_results:
          path: ./test-reports
      - store_artifacts:
          path: ./test-reports
