version: 2
jobs:
  build:
    working_directory: ~/angular-with-ci-cd-pipeline
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Testing [Unit]
          command: yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: Testing [End-to-End]
          command: yarn e2e -- --protractor-config=e2e/protractor-ci.conf.js
