version: 2
jobs:
  build:
    working_directory: ~/angular-with-ci-cd-pipeline
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
